driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  client_rb:
    environment: kitchen

platforms:

  - name: centos
    driver:
      provider: virtualbox
      box: boxcutter/centos66

suites:

  - name: default

    data_bags_path: test/chef/data_bags
    roles_path: test/chef/roles
    nodes_path: test/chef/nodes
    environments_path: test/chef/environments

    run_list:
      - role[chef-ha-frontend]

    attributes:
